### PR TITLE
Add compatibility with CakePHP 3.7 + Correct OracleOCI configuration

### PR DESCRIPTION
**Pull request by jmbIFR**
- Correct the Compatibility with CakePHP 3.6
- Add the Compatibility with CakePHP 3.7

Replace PR #35 and close issues #33 #34 #36

### CODE REVIEW

**Comment by sad148** [comment]
I implemented these changes for cakephp v3.7 and they work successfully.

**Comment by apricotpoodle** [comment]
I use your branch , thank you for compatibily with CakePHP 3.7. 

Just wanna tell about one issue. I already wrote in base branch. 

OCI8Connection: incomplete recognition of configuration ?

**DataSource configuration**, in config\app.php,  **is NOT 100% recognized**, 
especially options like charset, persistent, etc… 

Option charset is not recognized in this function :
https://github.com/CakeDC/cakephp-oracle-driver/blob/master/src/Database/OCI8/OCI8Connection.php#L55-59

because in file: 
https://github.com/CakeDC/cakephp-oracle-driver/blob/master/src/Database/Driver/OracleOCI.php#L20-30

There seems to be a typo.

protected function _connect($dsn, array $config)
    {
//**why only config[flags]** and not all **config** from DataSource in App.php ? 
//$connection = new OCI8Connection($dsn, $config['username'], $config['password'], **$config['flags']**); 

//SHOULD IT BE ?
$connection = new OCI8Connection($dsn, $config['username'], $config['password'], **$config**);

// now works fine for me and charset option is now recognized. 
// Solved my problem of charset conversion.

        $this->setconnection($connection);
        return true;
    }
 Anyway thanks for making the plugin by the way, works great!!

**Comment by harpax** [comment]
as well as with cakephp 3.8 as far as I was able to test.. Could this please be merged?!

**Comment by jmbIFR** [comment]
*  Correct the Compatibility with CakePHP 3.6
  *  Add the Compatibility with CakePHP 3.7
  *  Update README with correct configuration option
  *  correct the configuration for OracleOCI

close issues #33 #34 #36 #38 #40 #41

**Comment by skie** [comment]
applied in 4.x branch

**Pull request closed without merging**
